"""
Initial database migration: create all tables, indexes, and extensions.

This migration is hand-written (not autogenerated) to:
1. Enable the pgvector and pg_trgm extensions
2. Create a server-side trigger to populate the tsvector column
   (GENERATED ALWAYS AS ... STORED is not available in all Postgres
    versions Neon might use, so we use a trigger for compatibility)
3. Set up HNSW and GIN indexes with the correct operator classes

Revision ID: 0001
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── Extensions ──────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ── Papers ───────────────────────────────────────────────────────────────
    op.create_table(
        "papers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("source_filename", sa.String(512), nullable=False),
        sa.Column("arxiv_id", sa.String(50), nullable=True),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_filename"),
    )

    # ── Chunks ───────────────────────────────────────────────────────────────
    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunking_strategy", sa.String(50), nullable=False),
        sa.Column("embedding_model", sa.String(100), nullable=False),
        # Both models used here output 1024-dim vectors — see chunk.py for rationale.
        sa.Column("embedding", sa.Text(), nullable=True),  # placeholder; real type set below
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Replace the placeholder TEXT column with the real vector(1024) type
    op.execute("ALTER TABLE chunks DROP COLUMN embedding")
    op.execute("ALTER TABLE chunks ADD COLUMN embedding vector(1024)")

    # ── HNSW index on embedding vectors ─────────────────────────────────────
    # HNSW (Hierarchical Navigable Small World) gives sub-linear ANN search.
    # m=16: each node connects to 16 neighbours (higher = better recall, more memory)
    # ef_construction=64: build-time search breadth (higher = better quality index)
    op.execute("""
        CREATE INDEX idx_chunks_embedding_hnsw
        ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # ── GIN index on tsvector for full-text search ───────────────────────────
    op.execute("CREATE INDEX idx_chunks_tsv_gin ON chunks USING gin (tsv)")

    # ── Trigger to auto-update tsv when chunk_text changes ───────────────────
    op.execute("""
        CREATE OR REPLACE FUNCTION chunks_tsv_update() RETURNS trigger AS $$
        BEGIN
            NEW.tsv := to_tsvector('english', NEW.chunk_text);
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chunks_tsv_trigger
        BEFORE INSERT OR UPDATE OF chunk_text
        ON chunks
        FOR EACH ROW EXECUTE FUNCTION chunks_tsv_update()
    """)

    # ── Additional B-tree indexes ────────────────────────────────────────────
    op.create_index("idx_chunks_paper_id", "chunks", ["paper_id"])
    op.create_index("idx_chunks_embedding_model", "chunks", ["embedding_model"])
    op.create_index("idx_chunks_chunking_strategy", "chunks", ["chunking_strategy"])

    # ── Conversations ────────────────────────────────────────────────────────
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── Messages ─────────────────────────────────────────────────────────────
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "sources",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("retrieval_strategy", sa.String(50), nullable=True),
        sa.Column("embedding_model", sa.String(100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_conversation_id", "messages", ["conversation_id"])


def downgrade() -> None:
    op.drop_table("messages")
    op.drop_table("conversations")
    op.execute("DROP TRIGGER IF EXISTS chunks_tsv_trigger ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_tsv_update()")
    op.drop_table("chunks")
    op.drop_table("papers")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS vector")
